channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - detectron2=0.4
  - ffmpeg=4.0
  - ffmpeg-python=0.2.0
  - parse=1.19.0
  - pillow=7.2.0
  - pip=21.0.1
  - python=3.7
  - pyyaml=5.4.1
  - tqdm=4.59.0
  - numpy=1.20.2
  - pandas=1.2.3
  - opencv=3.4.2
  - pytorch=1.6.0
  - scikit-learn=0.24.1
  - torchvision=0.7.0
  - pip:
      - flickrapi==2.4.0
